<?xml version="1.0" encoding="utf-8"?>
<Database Name="udb" Class="udbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=FERLIN-PC\SQLEXPRESS;Initial Catalog=udb;Integrated Security=True" SettingsObjectName="UDBtoSpurious.My.MySettings" SettingsPropertyName="udbConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.creature_template" Member="creature_templates">
    <Type Name="creature_template">
      <Column Name="entry" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="difficulty_entry_1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="difficulty_entry_2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="difficulty_entry_3" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="KillCredit1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="KillCredit2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="modelid_A" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="modelid_A2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="modelid_H" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="modelid_H2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="Char(100) NOT NULL" CanBeNull="false" />
      <Column Name="subname" Type="System.String" DbType="Char(100)" CanBeNull="true" />
      <Column Name="IconName" Type="System.String" DbType="Char(100)" CanBeNull="true" />
      <Column Name="gossip_menu_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="minlevel" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="maxlevel" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="minhealth" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="maxhealth" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="minmana" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="maxmana" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="armor" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="faction_A" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="faction_H" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="npcflag" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="speed_walk" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="speed_run" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="scale" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="rank" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="mindmg" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="maxdmg" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="dmgschool" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="attackpower" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="dmg_multiplier" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="baseattacktime" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="rangeattacktime" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="unit_class" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="unit_flags" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="dynamicflags" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="family" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="trainer_type" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="trainer_spell" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="trainer_class" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="trainer_race" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="minrangedmg" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="maxrangedmg" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="rangedattackpower" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="type" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="type_flags" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="lootid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="pickpocketloot" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="skinloot" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="resistance1" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="resistance2" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="resistance3" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="resistance4" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="resistance5" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="resistance6" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="spell1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="spell2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="spell3" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="spell4" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PetSpellDataId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="mingold" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="maxgold" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AIName" Type="System.String" DbType="Char(64) NOT NULL" CanBeNull="false" />
      <Column Name="MovementType" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="InhabitType" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="unk16" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="unk17" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="RacialLeader" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="questItem1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="questItem2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="questItem3" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="questItem4" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="questItem5" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="questItem6" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="movementId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RegenHealth" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="equipment_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="mechanic_immune_mask" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="flags_extra" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ScriptName" Type="System.String" DbType="Char(64) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.creature" Member="creatures">
    <Type Name="creature">
      <Column Name="guid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="map" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="spawnMask" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="phaseMask" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="modelid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="equipment_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="position_x" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="position_y" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="position_z" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="orientation" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="spawntimesecs" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="spawndist" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="currentwaypoint" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="curhealth" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="curmana" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DeathState" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="MovementType" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.creature_equip_template" Member="creature_equip_templates">
    <Type Name="creature_equip_template">
      <Column Name="entry" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="equipentry1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="equipentry2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="equipentry3" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.creature_model_info" Member="creature_model_infos">
    <Type Name="creature_model_info">
      <Column Name="modelid" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="bounding_radius" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="combat_reach" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="gender" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="modelid_other_gender" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.creature_template_addon" Member="creature_template_addons">
    <Type Name="creature_template_addon">
      <Column Name="entry" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="mount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="bytes1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="bytes2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="emote" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="moveflags" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="auras" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.gameobject" Member="gameobjects">
    <Type Name="gameobject">
      <Column Name="guid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="map" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="spawnMask" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="phaseMask" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="position_x" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="position_y" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="position_z" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="orientation" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="rotation0" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="rotation1" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="rotation2" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="rotation3" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="spawntimesecs" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="animprogress" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="state" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.gameobject_template" Member="gameobject_templates">
    <Type Name="gameobject_template">
      <Column Name="entry" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="type" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="displayId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="IconName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="castBarCaption" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="unk1" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="faction" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="flags" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="size" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="questItem1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="questItem2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="questItem3" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="questItem4" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="questItem5" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="questItem6" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="data0" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="data1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="data2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="data3" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="data4" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="data5" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="data6" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="data7" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="data8" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="data9" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="data10" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="data11" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="data12" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="data13" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="data14" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="data15" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="data16" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="data17" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="data18" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="data19" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="data20" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="data21" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="data22" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="data23" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="mingold" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="maxgold" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ScriptName" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.item_template" Member="item_templates">
    <Type Name="item_template">
      <Column Name="entry" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="class" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="subclass" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="unk0" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="displayid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Quality" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Flags" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Faction" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BuyCount" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="BuyPrice" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SellPrice" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="InventoryType" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="AllowableClass" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AllowableRace" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ItemLevel" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="RequiredLevel" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="RequiredSkill" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="RequiredSkillRank" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="requiredspell" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="requiredhonorrank" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RequiredCityRank" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RequiredReputationFaction" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="RequiredReputationRank" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="maxcount" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="stackable" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="ContainerSlots" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="StatsCount" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="stat_type1" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="stat_value1" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="stat_type2" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="stat_value2" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="stat_type3" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="stat_value3" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="stat_type4" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="stat_value4" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="stat_type5" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="stat_value5" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="stat_type6" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="stat_value6" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="stat_type7" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="stat_value7" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="stat_type8" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="stat_value8" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="stat_type9" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="stat_value9" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="stat_type10" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="stat_value10" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="ScalingStatDistribution" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="ScalingStatValue" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="dmg_min1" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="dmg_max1" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="dmg_type1" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="dmg_min2" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="dmg_max2" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="dmg_type2" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="armor" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="holy_res" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="fire_res" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="nature_res" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="frost_res" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="shadow_res" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="arcane_res" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="delay" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="ammo_type" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="RangedModRange" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="spellid_1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="spelltrigger_1" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="spellcharges_1" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="spellppmRate_1" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="spellcooldown_1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="spellcategory_1" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="spellcategorycooldown_1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="spellid_2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="spelltrigger_2" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="spellcharges_2" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="spellppmRate_2" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="spellcooldown_2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="spellcategory_2" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="spellcategorycooldown_2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="spellid_3" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="spelltrigger_3" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="spellcharges_3" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="spellppmRate_3" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="spellcooldown_3" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="spellcategory_3" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="spellcategorycooldown_3" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="spellid_4" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="spelltrigger_4" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="spellcharges_4" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="spellppmRate_4" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="spellcooldown_4" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="spellcategory_4" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="spellcategorycooldown_4" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="spellid_5" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="spelltrigger_5" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="spellcharges_5" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="spellppmRate_5" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="spellcooldown_5" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="spellcategory_5" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="spellcategorycooldown_5" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="bonding" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="PageText" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LanguageID" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="PageMaterial" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="startquest" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="lockid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Material" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="sheath" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="RandomProperty" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RandomSuffix" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="block" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="itemset" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaxDurability" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="area" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Map" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="BagFamily" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TotemCategory" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="socketColor_1" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="socketContent_1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="socketColor_2" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="socketContent_2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="socketColor_3" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="socketContent_3" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="socketBonus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GemProperties" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RequiredDisenchantSkill" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="ArmorDamageModifier" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="Duration" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ItemLimitCategory" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="HolidayId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ScriptName" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="DisenchantID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FoodType" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="minMoneyLoot" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="maxMoneyLoot" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ExtraFlags" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.quest_template" Member="quest_templates">
    <Type Name="quest_template">
      <Column Name="entry" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Method" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="ZoneOrSort" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="SkillOrClass" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="MinLevel" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="QuestLevel" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="RequiredRaces" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="RequiredSkillValue" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="RepObjectiveFaction" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="RepObjectiveValue" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RequiredMinRepFaction" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="RequiredMinRepValue" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RequiredMaxRepFaction" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="RequiredMaxRepValue" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SuggestedPlayers" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="LimitTime" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="QuestFlags" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SpecialFlags" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="CharTitleId" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="PlayersSlain" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="BonusTalents" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="PrevQuestId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NextQuestId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ExclusiveGroup" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NextQuestInChain" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RewXPId" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="SrcItemId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SrcItemCount" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="SrcSpell" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Details" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Objectives" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="OfferRewardText" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="RequestItemsText" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="EndText" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CompletedText" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ObjectiveText1" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ObjectiveText2" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ObjectiveText3" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ObjectiveText4" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ReqItemId1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReqItemId2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReqItemId3" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReqItemId4" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReqItemId5" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReqItemId6" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReqItemCount1" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="ReqItemCount2" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="ReqItemCount3" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="ReqItemCount4" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="ReqItemCount5" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="ReqItemCount6" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="ReqSourceId1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReqSourceId2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReqSourceId3" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReqSourceId4" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReqSourceCount1" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="ReqSourceCount2" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="ReqSourceCount3" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="ReqSourceCount4" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="ReqCreatureOrGOId1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReqCreatureOrGOId2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReqCreatureOrGOId3" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReqCreatureOrGOId4" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReqCreatureOrGOCount1" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="ReqCreatureOrGOCount2" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="ReqCreatureOrGOCount3" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="ReqCreatureOrGOCount4" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="ReqSpellCast1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReqSpellCast2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReqSpellCast3" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReqSpellCast4" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RewChoiceItemId1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RewChoiceItemId2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RewChoiceItemId3" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RewChoiceItemId4" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RewChoiceItemId5" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RewChoiceItemId6" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RewChoiceItemCount1" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="RewChoiceItemCount2" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="RewChoiceItemCount3" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="RewChoiceItemCount4" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="RewChoiceItemCount5" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="RewChoiceItemCount6" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="RewItemId1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RewItemId2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RewItemId3" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RewItemId4" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RewItemCount1" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="RewItemCount2" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="RewItemCount3" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="RewItemCount4" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="RewRepFaction1" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="RewRepFaction2" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="RewRepFaction3" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="RewRepFaction4" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="RewRepFaction5" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="RewRepValueId1" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="RewRepValueId2" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="RewRepValueId3" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="RewRepValueId4" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="RewRepValueId5" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="RewRepValue1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RewRepValue2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RewRepValue3" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RewRepValue4" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RewRepValue5" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RewHonorAddition" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RewHonorMultiplier" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="RewOrReqMoney" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RewMoneyMaxLevel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RewSpell" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RewSpellCast" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RewMailTemplateId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RewMailDelaySecs" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PointMapId" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="PointX" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="PointY" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="PointOpt" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DetailsEmote1" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="DetailsEmote2" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="DetailsEmote3" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="DetailsEmote4" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="DetailsEmoteDelay1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DetailsEmoteDelay2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DetailsEmoteDelay3" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DetailsEmoteDelay4" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IncompleteEmote" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="CompleteEmote" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="OfferRewardEmote1" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="OfferRewardEmote2" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="OfferRewardEmote3" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="OfferRewardEmote4" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="OfferRewardEmoteDelay1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OfferRewardEmoteDelay2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OfferRewardEmoteDelay3" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OfferRewardEmoteDelay4" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StartScript" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CompleteScript" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.battlemaster_entry" Member="battlemaster_entries">
    <Type Name="battlemaster_entry">
      <Column Name="entry" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="bg_template" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.battleground_template" Member="battleground_templates">
    <Type Name="battleground_template">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MinPlayersPerTeam" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="MaxPlayersPerTeam" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="AllianceStartLoc" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AllianceStartO" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="HordeStartLoc" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HordeStartO" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.areatrigger_involvedrelation" Member="areatrigger_involvedrelations">
    <Type Name="areatrigger_involvedrelation">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="quest" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.areatrigger_tavern" Member="areatrigger_taverns">
    <Type Name="areatrigger_tavern">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.areatrigger_teleport" Member="areatrigger_teleports">
    <Type Name="areatrigger_teleport">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="required_level" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="required_item" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="required_item2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="heroic_key" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="heroic_key2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="required_quest_done" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="required_quest_done_heroic" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="required_failed_text" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="target_map" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="target_position_x" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="target_position_y" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="target_position_z" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="target_orientation" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.spell_target_position" Member="spell_target_positions">
    <Type Name="spell_target_position">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="target_map" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="target_position_x" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="target_position_y" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="target_position_z" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="target_orientation" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.npc_gossip" Member="npc_gossips">
    <Type Name="npc_gossip">
      <Column Name="npc_guid" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="textid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.npc_trainer" Member="npc_trainers">
    <Type Name="npc_trainer">
      <Column Name="entry" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="spell" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="spellcost" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="reqskill" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="reqskillvalue" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="reqlevel" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.npc_vendor" Member="npc_vendors">
    <Type Name="npc_vendor">
      <Column Name="entry" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="item" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maxcount" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="incrtime" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ExtendedCost" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.npc_text" Member="npc_texts">
    <Type Name="npc_text">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="text0_0" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="text0_1" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="lang0" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="prob0" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="em0_0" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="em0_1" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="em0_2" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="em0_3" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="em0_4" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="em0_5" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="text1_0" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="text1_1" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="lang1" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="prob1" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="em1_0" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="em1_1" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="em1_2" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="em1_3" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="em1_4" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="em1_5" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="text2_0" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="text2_1" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="lang2" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="prob2" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="em2_0" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="em2_1" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="em2_2" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="em2_3" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="em2_4" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="em2_5" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="text3_0" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="text3_1" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="lang3" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="prob3" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="em3_0" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="em3_1" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="em3_2" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="em3_3" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="em3_4" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="em3_5" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="text4_0" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="text4_1" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="lang4" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="prob4" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="em4_0" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="em4_1" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="em4_2" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="em4_3" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="em4_4" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="em4_5" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="text5_0" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="text5_1" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="lang5" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="prob5" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="em5_0" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="em5_1" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="em5_2" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="em5_3" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="em5_4" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="em5_5" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="text6_0" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="text6_1" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="lang6" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="prob6" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="em6_0" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="em6_1" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="em6_2" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="em6_3" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="em6_4" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="em6_5" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="text7_0" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="text7_1" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="lang7" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="prob7" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="em7_0" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="em7_1" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="em7_2" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="em7_3" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="em7_4" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="em7_5" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.npc_spellclick_spells" Member="npc_spellclick_spells">
    <Type Name="npc_spellclick_spell">
      <Column Name="npc_entry" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="spell_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="quest_start" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="quest_start_active" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="quest_end" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="cast_flags" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.creature_questrelation" Member="creature_questrelations">
    <Type Name="creature_questrelation">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="quest" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.creature_involvedrelation" Member="creature_involvedrelations">
    <Type Name="creature_involvedrelation">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="quest" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.gameobject_questrelation" Member="gameobject_questrelations">
    <Type Name="gameobject_questrelation">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="quest" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.gameobject_involvedrelation" Member="gameobject_involvedrelations">
    <Type Name="gameobject_involvedrelation">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="quest" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.game_weather" Member="game_weathers">
    <Type Name="game_weather">
      <Column Name="zone" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="spring_rain_chance" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="spring_snow_chance" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="spring_storm_chance" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="summer_rain_chance" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="summer_snow_chance" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="summer_storm_chance" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="fall_rain_chance" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="fall_snow_chance" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="fall_storm_chance" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="winter_rain_chance" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="winter_snow_chance" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="winter_storm_chance" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.page_text" Member="page_texts">
    <Type Name="page_text">
      <Column Name="entry" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="text" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="next_page" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.player_classlevelstats" Member="player_classlevelstats">
    <Type Name="player_classlevelstat">
      <Column Name="class" Type="System.Byte" DbType="TinyInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[level]" Member="level" Type="System.Byte" DbType="TinyInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="basehp" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="basemana" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.player_levelstats" Member="player_levelstats">
    <Type Name="player_levelstat">
      <Column Name="race" Type="System.Byte" DbType="TinyInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="class" Type="System.Byte" DbType="TinyInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[level]" Member="level" Type="System.Byte" DbType="TinyInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="str" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="agi" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="sta" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="inte" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="spi" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.playercreateinfo" Member="playercreateinfos">
    <Type Name="playercreateinfo">
      <Column Name="race" Type="System.Byte" DbType="TinyInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="class" Type="System.Byte" DbType="TinyInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="map" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="zone" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="position_x" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="position_y" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="position_z" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.playercreateinfo_action" Member="playercreateinfo_actions">
    <Type Name="playercreateinfo_action">
      <Column Name="race" Type="System.Byte" DbType="TinyInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="class" Type="System.Byte" DbType="TinyInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="button" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="action" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="type" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.playercreateinfo_item" Member="playercreateinfo_items">
    <Type Name="playercreateinfo_item">
      <Column Name="race" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="class" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="itemid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="amount" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.playercreateinfo_spell" Member="playercreateinfo_spells">
    <Type Name="playercreateinfo_spell">
      <Column Name="race" Type="System.Byte" DbType="TinyInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="class" Type="System.Byte" DbType="TinyInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Spell" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Note" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.skinning_loot_template" Member="skinning_loot_templates">
    <Type Name="skinning_loot_template">
      <Column Name="entry" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="item" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ChanceOrQuestChance" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="groupid" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="mincountOrRef" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="maxcount" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="lootcondition" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="condition_value1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="condition_value2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.gameobject_loot_template" Member="gameobject_loot_templates">
    <Type Name="gameobject_loot_template">
      <Column Name="entry" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="item" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ChanceOrQuestChance" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="groupid" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="mincountOrRef" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="maxcount" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="lootcondition" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="condition_value1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="condition_value2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.creature_loot_template" Member="creature_loot_templates">
    <Type Name="creature_loot_template">
      <Column Name="entry" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="item" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ChanceOrQuestChance" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="groupid" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="mincountOrRef" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="maxcount" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="lootcondition" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="condition_value1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="condition_value2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.item_loot_template" Member="item_loot_templates">
    <Type Name="item_loot_template">
      <Column Name="entry" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="item" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ChanceOrQuestChance" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="groupid" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="mincountOrRef" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="maxcount" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="lootcondition" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="condition_value1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="condition_value2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.creature_movement" Member="creature_movements">
    <Type Name="creature_movement">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="point" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="position_x" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="position_y" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="position_z" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="waittime" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="script_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="textid1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="textid2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="textid3" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="textid4" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="textid5" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="emote" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="spell" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="wpguid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="orientation" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="model1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="model2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>